DELETE FROM `wk_tbl_partner_corp_add_min`;
ALTER TABLE `wk_tbl_partner_corp_add_min` auto_increment = 0;
INSERT INTO `wk_tbl_partner_corp_add_min` (`wk_tbl_partner_corp_add_min_id`,`wk_tbl_partner_corp_add_min_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`houjin_no`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (102,102,1,1,'a','b','c','11',1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_partner_corp_add_min` (`wk_tbl_partner_corp_add_min_id`,`wk_tbl_partner_corp_add_min_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`houjin_no`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (103,102,1,1,'a','b','d','11',1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_partner_corp_add_min` (`wk_tbl_partner_corp_add_min_id`,`wk_tbl_partner_corp_add_min_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`houjin_no`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (104,102,1,1,'a','b','e','11',1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_partner_corp_add_min` (`wk_tbl_partner_corp_add_min_id`,`wk_tbl_partner_corp_add_min_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`houjin_no`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (105,102,1,1,'a','b','f','11',1,'理由',303,293,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');


INSERT INTO `wk_tbl_partner_corp_add_min` (`wk_tbl_partner_corp_add_min_id`,`wk_tbl_partner_corp_add_min_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`houjin_no`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (501,102,1,1,'a','b','c','11',1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_partner_corp_add_min` (`wk_tbl_partner_corp_add_min_id`,`wk_tbl_partner_corp_add_min_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`houjin_no`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (502,102,1,1,'a','b','c','11',1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');

INSERT INTO `wk_tbl_partner_corp_add_min` (`wk_tbl_partner_corp_add_min_id`,`wk_tbl_partner_corp_add_min_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`houjin_no`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (601,102,1,1,'a','b','d','11',1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
