DELETE FROM `wk_tbl_master_person`;
ALTER TABLE `wk_tbl_master_person` auto_increment = 0;
INSERT INTO `wk_tbl_master_person` (`wk_tbl_master_person_id`,`wk_tbl_master_person_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postal_code`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`is_foreign`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (296,278,1,1,'a','b','w','d','e','f','g','h','i','j','k','l','m','n','o','p','q',326,246,'t','u',' v',1,1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_master_person` (`wk_tbl_master_person_id`,`wk_tbl_master_person_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postal_code`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`is_foreign`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (297,278,1,1,'a','b','x','d','e','f','g','h','i','j','k','l','m','n','o','p','q',326,246,'t','u',' v',1,1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_master_person` (`wk_tbl_master_person_id`,`wk_tbl_master_person_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postal_code`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`is_foreign`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (298,278,1,1,'a','b','y','d','e','f','g','h','i','j','k','l','m','n','o','p','q',326,246,'t','u',' v',1,1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_master_person` (`wk_tbl_master_person_id`,`wk_tbl_master_person_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postal_code`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`is_foreign`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (299,278,1,1,'a','b','z','d','e','f','g','h','i','j','k','l','m','n','o','p','q',326,246,'t','u',' v',1,1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');

INSERT INTO `wk_tbl_master_person` (`wk_tbl_master_person_id`,`wk_tbl_master_person_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postal_code`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`is_foreign`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (501,278,1,1,'a','b','w','d','e','f','g','h','i','j','k','l','m','n','o','p','q',326,246,'t','u',' v',1,1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_master_person` (`wk_tbl_master_person_id`,`wk_tbl_master_person_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postal_code`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`is_foreign`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (502,278,1,1,'a','b','w','d','e','f','g','h','i','j','k','l','m','n','o','p','q',326,246,'t','u',' v',1,1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');

INSERT INTO `wk_tbl_master_person` (`wk_tbl_master_person_id`,`wk_tbl_master_person_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postal_code`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`is_foreign`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (601,278,1,1,'a','b','x','d','e','f','g','h','i','j','k','l','m','n','o','p','q',326,246,'t','u',' v',1,1,'理由',215,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');

