DELETE FROM `master_corporation_access`;
ALTER TABLE `master_corporation_access` auto_increment = 0;

INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2601,NULL,'9-6X98-66','テスト法人',1,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');

INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2611,NULL,'1-3Keh5-94','テスト法人',0,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');
INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2612,NULL,'1-3Keh5-94','テスト法人',0,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');
INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2613,NULL,'1-3Keh5-94','テスト法人',1,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');
INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2614,NULL,'1-3Keh5-94','テスト法人',1,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');

INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2621,NULL,'6-2ar95-6L7','テスト法人',0,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');
INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2622,NULL,'6-2ar95-6L7','テスト法人',0,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');
INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2623,NULL,'6-2ar95-6L7','テスト法人',0,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');
INSERT INTO `master_corporation_access` (`master_corporation_access_id`,`master_corporation_id`,`corp_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (2624,NULL,'6-2ar95-6L7','テスト法人',0,'012','345','6789','aaa@example.com','https://example.com/blog',0,0,'弱小SNS','https://example.com/?acount=222','@corp',213,190,'管理人　太郎','2025-09-13 05:40:46',0,0,'ユーザ','1948-07-28 23:00:00');
