DELETE FROM `master_political_organization_access`;
ALTER TABLE `master_political_organization_access` auto_increment = 0;

INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (601,0,'7A8-6pg98-66','テスト政治団体1',1,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');

INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (611,0,'3U9-3G46eh5-94','テスト政治団体1',0,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');
INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (612,0,'3U9-3G46eh5-94','テスト政治団体1',0,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');
INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (613,0,'3U9-3G46eh5-94','テスト政治団体1',1,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');
INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (614,0,'3U9-3G46eh5-94','テスト政治団体1',1,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');

INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (621,0,'1H3-4asx95-6L7','テスト政治団体1',0,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');
INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (622,0,'1H3-4asx95-6L7','テスト政治団体1',0,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');
INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (623,0,'1H3-4asx95-6L7','テスト政治団体1',0,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');
INSERT INTO `master_political_organization_access` (`master_political_organization_access_id`,`master_political_organization_id`,`poli_org_kanrensha_code`,`partner_name`,`is_latest`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_id`,`sns_service_code`,`sns_service_name`,`sns_portal_url`,`sns_account`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (624,0,'1H3-4asx95-6L7','テスト政治団体1',1,'012','345','6789','org1@example.com','https://example.com/org1',0,0,'テストSNS','https://sns.example.com','@org1',213,190,'ユーザ','2025-09-13 05:25:03',0,0,'ユーザ','2025-09-13 05:25:03');
