CREATE TABLE `houjin_no_history` (
  `houjin_no_history_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `houjin_no_latest_id` bigint DEFAULT NULL COMMENT 'テーブルId',
  `corporate_number` varchar(15) DEFAULT NULL COMMENT '法人番号',
  `process` varchar(4) DEFAULT NULL COMMENT '処理区分',
  `correct` tinyint DEFAULT NULL COMMENT '訂正区分',
  `update_date` date DEFAULT NULL COMMENT '更新年月日',
  `change_date` date DEFAULT NULL COMMENT '変更年月日',
  `name` varchar(200) DEFAULT NULL COMMENT '商号又は名称',
  `kind` varchar(5) DEFAULT NULL COMMENT '法人種別',
  `prefecture_name` varchar(12) DEFAULT NULL COMMENT '国内所在地（都道府県）',
  `city_name` varchar(22) DEFAULT NULL COMMENT '国内所在地（市区町村）',
  `street_number` text COMMENT '国内所在地（丁目番地等）',
  `prefecture_code` varchar(4) DEFAULT NULL COMMENT '都道府県コード',
  `city_code` varchar(5) DEFAULT NULL COMMENT '市区町村コード',
  `post_code` varchar(9) DEFAULT NULL COMMENT '郵便番号',
  `address_outside` text COMMENT '国外所在地',
  `close_date` date DEFAULT NULL COMMENT '登記記録の閉鎖等年月日',
  `close_cause` varchar(2) DEFAULT NULL COMMENT '登記記録の閉鎖等の事由',
  `successor_corporate_number` varchar(15) DEFAULT NULL COMMENT '承継先法人番号',
  `change_cause` text COMMENT '変更事由の詳細',
  `assignment_date` date DEFAULT NULL COMMENT '法人番号指定年月日',
  `latest` tinyint DEFAULT NULL COMMENT '最新履歴',
  `furigana` text COMMENT 'フリガナ',
  `hihyoji` tinyint DEFAULT NULL COMMENT '検索対象除外',
  PRIMARY KEY (`houjin_no_history_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
