CREATE TABLE `master_person_base` (
  `master_person_base_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `master_person_id` int DEFAULT NULL COMMENT '関連者個人Id',
  `person_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '関連者個人コード',
  `partner_name` varchar(200) DEFAULT NULL COMMENT '関連者個人名称',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `last_name` varchar(100) DEFAULT NULL COMMENT '姓名の姓',
  `first_name` varchar(100) DEFAULT NULL COMMENT '姓名の名',
  `middle_name` varchar(100) DEFAULT NULL COMMENT '姓名のミドルネーム',
  `last_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名の姓かな',
  `first_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名の名かな',
  `middle_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名のミドルネームかな',
  `gyoushu` varchar(100) DEFAULT NULL COMMENT '職業の業種',
  `yakushoku` varchar(100) DEFAULT NULL COMMENT '職業の役職',
  `shokugyou_user_write` varchar(100) DEFAULT NULL COMMENT 'ユーザ記述の職業',
  `corp_no` varchar(100) DEFAULT NULL COMMENT '企業番号',
  `corp_address` varchar(100) DEFAULT NULL COMMENT '企業所在地',
  `corp_name` varchar(100) DEFAULT NULL COMMENT '企業名',
  `is_shokyou_edit` tinyint DEFAULT NULL COMMENT '職業編集該否',
  `is_shokyou_accept` tinyint DEFAULT NULL COMMENT '職業編集承認該否',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`master_person_base_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
