CREATE TABLE `master_person_address` (
  `master_person_address_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `master_person_id` int DEFAULT NULL COMMENT '関連者個人Id',
  `person_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '関連者個人コード',
  `partner_name` varchar(200) DEFAULT NULL COMMENT '関連者個人名称',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `address_postal` text COMMENT '住所郵便番号',
  `address_block` text COMMENT '住所番地',
  `address_building` text COMMENT '住所建物',
  `postal1` varchar(8) DEFAULT NULL COMMENT '郵便番号1',
  `postal2` varchar(8) DEFAULT NULL COMMENT '郵便番号2',
  `lg_code` varchar(8) DEFAULT NULL COMMENT '地方自治体コード',
  `machiaza_id` varchar(9) DEFAULT NULL COMMENT '町字コード',
  `blk_id` varchar(5) DEFAULT NULL COMMENT '街区コード',
  `rsdt_id` varchar(5) DEFAULT NULL COMMENT '住居コード',
  `rsdt2_id` varchar(7) DEFAULT NULL COMMENT '住居2コード',
  `is_postal_edit` tinyint DEFAULT NULL COMMENT '住所郵便番号編集該否',
  `is_block_edit` tinyint DEFAULT NULL COMMENT '住所番地編集該否',
  `is_building_edit` tinyint DEFAULT NULL COMMENT '住所建物編集該否',
  `is_postal_accept` tinyint DEFAULT NULL COMMENT '住所郵便番号承認該否',
  `is_block_accept` tinyint DEFAULT NULL COMMENT '住所番地承認該否',
  `is_building_accept` tinyint DEFAULT NULL COMMENT '住所建物承認該否',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`master_person_address_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
