CREATE TABLE `riyousha_comrade_name` (
  `riyousha_comrade_name_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `riyousha_comrade_id` int DEFAULT NULL COMMENT '利用者管理者Id',
  `riyousha_comrade_code` int DEFAULT NULL COMMENT '利用者管理者コード',
  `riyousha_comrade_name` varchar(200) DEFAULT NULL COMMENT '利用者管理者名称',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `is_not_org` tinyint DEFAULT NULL COMMENT '組織非該当',
  `last_name` varchar(100) DEFAULT NULL COMMENT '姓名の姓',
  `first_name` varchar(100) DEFAULT NULL COMMENT '姓名の名',
  `middle_name` varchar(100) DEFAULT NULL COMMENT '姓名のミドルネーム',
  `last_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名の姓かな',
  `first_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名の名かな',
  `middle_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名のミドルネームかな',
  `org_name` varchar(200) DEFAULT NULL COMMENT '組織名称',
  `org_name_kana` varchar(200) DEFAULT NULL COMMENT '組織名称かな',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`riyousha_comrade_name_id`)
) ENGINE=InnoDB AUTO_INCREMENT=317 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
