DELETE FROM `wk_tbl_partner_poli_org_history`;
ALTER TABLE `wk_tbl_partner_poli_org_history` auto_increment = 0;

INSERT INTO `wk_tbl_partner_poli_org_history` (`wk_partner_poli_org_history_id`,`wk_partner_poli_org_history_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`poli_org_delegate`,`poli_org_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (313,311,1,1,'a','b','c','w',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_partner_poli_org_history` (`wk_partner_poli_org_history_id`,`wk_partner_poli_org_history_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`poli_org_delegate`,`poli_org_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (314,311,1,1,'a','b','c','x',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_partner_poli_org_history` (`wk_partner_poli_org_history_id`,`wk_partner_poli_org_history_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`poli_org_delegate`,`poli_org_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (315,311,1,1,'a','b','c','y',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_partner_poli_org_history` (`wk_partner_poli_org_history_id`,`wk_partner_poli_org_history_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`poli_org_delegate`,`poli_org_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (316,311,1,1,'a','b','c','z',1,'理由',253,219,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');

INSERT INTO `wk_tbl_partner_poli_org_history` (`wk_partner_poli_org_history_id`,`wk_partner_poli_org_history_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`poli_org_delegate`,`poli_org_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (501,311,1,1,'a','b','c','w',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');
INSERT INTO `wk_tbl_partner_poli_org_history` (`wk_partner_poli_org_history_id`,`wk_partner_poli_org_history_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`poli_org_delegate`,`poli_org_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (502,311,1,1,'a','b','c','w',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');

INSERT INTO `wk_tbl_partner_poli_org_history` (`wk_partner_poli_org_history_id`,`wk_partner_poli_org_history_code`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`poli_org_delegate`,`poli_org_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (601,311,1,1,'a','b','c','x',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'ユーザ','1948-07-29 00:00:00');

