DELETE FROM `wk_tbl_partner_corp_history`;
ALTER TABLE `wk_tbl_partner_corp_history` auto_increment = 0;
INSERT INTO `wk_tbl_partner_corp_history` (`wk_partner_corp_history_id`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`corp_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (101,1,1,'a','b','c','w',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'1','1948-07-28 00:00:00');
INSERT INTO `wk_tbl_partner_corp_history` (`wk_partner_corp_history_id`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`corp_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (102,1,1,'a','b','c','x',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'1','1948-07-28 00:00:00');
INSERT INTO `wk_tbl_partner_corp_history` (`wk_partner_corp_history_id`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`corp_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (103,1,1,'a','b','c','y',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'1','1948-07-28 00:00:00');
INSERT INTO `wk_tbl_partner_corp_history` (`wk_partner_corp_history_id`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`corp_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (104,1,1,'a','b','c','z',1,'理由',255,219,'ユーザ','2022-12-05 12:34:56',1,1,'1','1948-07-28 00:00:00');

INSERT INTO `wk_tbl_partner_corp_history` (`wk_partner_corp_history_id`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`corp_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (501,1,1,'a','b','c','w',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'1','1948-07-28 00:00:00');
INSERT INTO `wk_tbl_partner_corp_history` (`wk_partner_corp_history_id`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`corp_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (502,1,1,'a','b','c','w',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'1','1948-07-28 00:00:00');

INSERT INTO `wk_tbl_partner_corp_history` (`wk_partner_corp_history_id`,`is_latest`,`is_finish`,`partner_name`,`all_address`,`corp_delegate`,`corp_kanrensha_code`,`is_affected`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (601,1,1,'a','b','c','x',1,'理由',200,190,'ユーザ','2022-12-05 12:34:56',1,1,'1','1948-07-28 00:00:00');

